org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=D:/GAMES/minecraft/java/jdk-25.0.3
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.14
fabric_api_version=0.155.0+26.2
modmenu_version=20.0.1
jade_version=26.2.9+fabric

mod_version=1.0.0
maven_group=br.com.smarttrade
archives_base_name=smarttrade
